### ISSUE TITLE
Im lost how to install

### ISSUE THREAD

**Issue by function0x260edd** [kpcyrd/laundry5#2]
I am not good at coding or even know much at all, there are minimal instructions, I have installed rust, and also copy and pasted the commands 
    laundry5 -v -B 127.0.0.1:1337 -L ./pr0xies.txt
Into cmd, it does nothing, could you elaborate on how to install this properly?

**Comment by kpcyrd** [comment]
Running the following commands should work:

```sh
# if you don't have a Rust compiler yet, use either something like `pacman -S cargo` or this:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# clone the repo and build
git clone https://github.com/kpcyrd/laundry5
cd laundry5
cargo build --release
# run the binary
./target/release/laundry5 --help
```

This works for almost any Rust project, you can then copy the binary from `./target/release/laundry5` to a different computer, copy it into `/usr/bin/` or at `~/bin` inside of your home directory.

Feel free to ask if anything is unclear, hopefully these instruction just work™ though. :)

**Comment by function0x260edd** [comment]
It doesnt work for me, please explain like im a toddler, I pasted into command prompt, you mention rust, I was researching that,  and I did pip install, but the commands still didnt work
